# vhr-cloudmask conda environment
# Modify gdal version based on the systems installed library.
# Author: Jordan A. Caraballo-Vega, Science Data Processing Branch, 587
name: vhr-cloudmask

channels:
  - conda-forge
  - defaults
  - anaconda

dependencies:
  - cudatoolkit=10.2
  - cudnn
  - pip:
    - numpy
    - pandas
    - matplotlib
    - scikit-image
    - scikit-learn
    - rasterio
    - xarray
    - dask
    - opencv-python
    - imutils
    #- pygdal==3.0.4.6
    - pygdal=2.2.2
    - hummingbird-ml
