# vhr-cloudmask conda environment
# Modify gdal version based on the systems installed library.
# Author: Jordan A. Caraballo-Vega, Science Data Processing Branch, 587
name: vhr-cloudmask

channels:
  - conda-forge
  - defaults
  - anaconda

dependencies:
  - cudatoolkit=10.2
  - cudnn
  - pip:
    - numpy
    - pandas
    - scikit-learn
    - rasterio
    - xarray
    - dask[complete]
    - opencv-python
    - imutils
    - hummingbird-ml
    - joblib
    - toolz