# definition file to build xrasterlib conda environment
name: xrasterlib

channels:
  - conda-forge
  - defaults
  - anaconda
  - rapidsai
  - nvidia

dependencies:
  - rapids-blazing=0.17
  - python=3.7
  - cudatoolkit=10.1
  - Pillow
  - pip
  - pip:
    - tensorflow==2.3
    - opencv-python
    - scikit-image
    - tifffile
    - seaborn
    - scipy
    - Pillow
    - imagecodecs
    - rasterio
    - webcolors
    - tqdm
    - pdoc3
    - flake8
    - coverage
    - numba
