# definition file to build xrasterlib conda environment
name: xrasterlib

channels:
  - conda-forge
  - defaults
  - anaconda
  - rapidsai
  - nvidia

dependencies:
  - rapids-blazing=0.17
  - python=3.7
  - cudatoolkit=10.1
  - tensorflow
  - webcolors
  - Pillow
  - pip
  - pip:
    - tensorflow
    - opencv-python
    - scikit-image
    - tifffile
    - seaborn
    - scipy
    - Pillow
    - imagecodecs
    - rasterio